#!/bin/bash
export NO_ENSURE_TREESITTER=1
nvim --headless \
  +"call denops#server#start()" \
  +"call denops#server#wait()" \
  +'autocmd User Dpp:makeStatePost qall'
while :;
do
    notinstalled=$(
        nvim --headless \
        +"call denops#server#start()" \
        +"call denops#server#wait()" \
        +"echo dpp#sync_ext_action('installer', 'getNotInstalled')" \
        +qall 2>&1
    )
    if [ "$notinstalled" != "[]" ];then
        nvim --headless \
            +"call denops#server#start()" \
            +"call denops#server#wait()" \
            +'autocmd User Dpp:makeStatePost qall' \
            +"call dpp#sync_ext_action('installer', 'install')"
    else
        break
    fi
done
nvim --headless \
  +"call denops#server#start()" \
  +"call denops#server#wait()" \
  +"call dpp#source('denops-shared-server.vim')" \
  +"call denops_shared_server#install()" \
  +qall
coc_plugins=$(nvim --headless +"echo coc_global_extensions" +qa 2>&1 | sed "s/'/\"/g" | jq -r .[])
while :;
do
  need_reinstall=0
  nvim --headless +"call coc#rpc#request('installExtensions', g:coc_global_extensions)" +qall
  for plugin in ${coc_plugins[@]}
  do
    if [ ! -d ~/.config/coc/extensions/"node_modules/${plugin}" ];then
      need_reinstall=1
    fi
  done
  if [ "$need_reinstall" = "0" ];then
    break
  fi
done
unset NO_ENSURE_TREESITTER
while :;
do
  ts_inst_log=$(nvim --headless +TSUpdateSync +qall 2>&1 | grep -v 'up-to-date')
  if [ "$ts_inst_log" = "" ];then
    break
  fi
done
