[[plugins]]
repo = 'vim-denops/denops.vim'
hook_source = '''
  let g:denops#debug = v:false
  echom "121212"

  let g:denops#server#deno_args = [
      \   '-q',
      \   '-A',
      \ ]

  " NOTE: for Deno KV storage
  let g:denops#server#deno_args += ['--unstable-kv']

  " NOTE: for profile
  "let g:denops#server#deno_args += ['--inspect']

  " NOTE: for denops-silicon
  "let g:denops#server#deno_args += ['--unstable-ffi']

  "let g:denops_server_addr = '127.0.0.1:32123'
'''

[[plugins]]
repo = 'vim-denops/denops-startup-recorder.vim'
on_source = 'denops.vim'
