[[plugins]]
repo = 'vim-denops/denops.vim'
hooks_file = "$BASE_DIR/lua/plugins/denops.lua"
# on_source = "vim-denops/denops-shared-server.vim"

[[plugins]]
repo = "vim-denops/denops-shared-server.vim"
on_event = 'BufRead'
depends = 'denops.vim'
hooks_file = "$BASE_DIR/lua/plugins/denops-shared-server.lua"

[[plugins]]
repo = 'vim-denops/denops-startup-recorder.vim'
on_source = 'denops.vim'
