[[plugins]]
repo = 'toppair/peek.nvim'
on_cmd = 'MdPreview'
hooks_file = "$BASE_DIR/lua/plugins/peek.lua"
extAttrs = { installerBuild = 'deno task --quiet build:fast' }

### LSP Section
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_event = ['InsertEnter', 'CmdlineEnter', 'CursorHold']
hooks_file = "$BASE_DIR/lua/plugins/coc.lua"
### LSP END

### Snippet Section
### Count: 2
[[plugins]]
repo = 'ssfdust/neosnippet-snippets'
on_event = ['InsertEnter', 'CmdlineEnter']

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = ['InsertEnter', 'CmdlineEnter']

### Snippet END
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['CursorHold', 'InsertEnter', 'CmdlineEnter']
hooks_file = "$BASE_DIR/lua/plugins/treesitter.lua"

[[plugins]]
repo = 'Exafunction/codeium.vim'
on_event = ['InsertEnter']
hooks_file = "$BASE_DIR/lua/plugins/codeium.lua"

[[plugins]]
repo = 'Shougo/cmdline.vim'
on_source = ['ddu.vim']
hooks_file = "$BASE_DIR/lua/plugins/cmdline.lua"

[[plugins]]
repo = 'lilydjwg/fcitx.vim'
on_event = ['InsertEnter']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['G', 'G*']

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
on_event = ['AlphaClosed', 'BufRead', 'BufNewFile']
hooks_file = "$BASE_DIR/lua/plugins/lualine.lua"
