[[plugins]]
repo = 'airblade/vim-rooter'
hooks_file = "$BASE_DIR/lua/plugins/rooter.lua"

[[plugins]]
repo = 'antoyo/vim-licenses'
hooks_file = "$BASE_DIR/lua/plugins/licenses.lua"

[[plugins]]
repo = 'Shougo/deol.nvim'
hooks_file = "$BASE_DIR/lua/plugins/deol.lua"

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'goolord/alpha-nvim'
hooks_file = "$BASE_DIR/lua/plugins/alpha.lua"

[[plugins]]
repo = 'rebelot/kanagawa.nvim'

[[plugins]]
repo = 'ap/vim-css-color'
###
