[[plugins]]
repo = 'neovim/nvim-lspconfig'
hooks_file = '$BASE_DIR/lua/plugins/nvim-lspconfig.lua'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'nvim-lspconfig'
depends = 'ddc-source-lsp'
hooks_file = '$BASE_DIR/lua/plugins/mason-lspconfig.lua'

[[plugins]]
repo = 'williamboman/mason.nvim'
depends = 'nvim-lspconfig'
on_event = 'FileType'
on_if = '&filetype != "alpha"'
hooks_file = '$BASE_DIR/lua/plugins/mason.lua'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['CursorHold', 'BufRead']
hooks_file = "$BASE_DIR/lua/plugins/treesitter.lua"
